### ISSUE TITLE
things that aren't listed in the npc's shop

### ISSUE THREAD

**Issue by KDDoki** [Hatoskahun/woodcraftmc#2]
emerald,  arany tojás, rotten flesh,  közeledik a tél,rózsa vagy pipacs, fogalmam sincs melyik van bent 1.8 ban... tojás, ( két potato van a listában 1 helyett ) , mystic kard.. glowstone, redstone, arrow, feather,  hógolyó, szekerce,  obsidian, name tag, istenek horgászbotja, maja kard, maja íj, aaz az íj ami legendary, és a lvl8 as havasi zombik dobják, saddle....

**Comment by Hatoskahun** [comment]
Emeraldot nem is lehet majd eladni, rózsa küldi cucc glowstone egyelőre nem beszerezhető, szintúgy a redstone sem. Arrow-ot alapból nem lehet eladni. Tollat hozzáadtam, hógolyót,szekercéket,obszidiánt,maja kardot, maja íjat, mystic kardot is. A nyerget meg nem lehet eladni.
